### ISSUE TITLE
Issues when adding an image to the canvas ()

### ISSUE THREAD

**Issue by luigimalago** [asotog/fabricjs-react#47]
Dear all,
I have an issue when adding an image to a canvas. I modified the code from the sandbox, however I got an error when the cursor is over the image. Can you please provide some feedback?

This is the error I obtain

```
fabric.js:13911 Uncaught TypeError: target._findTargetCorner is not a function
    at klass._setCursorFromEvent (fabric.js:13911:1)
    at klass.__onMouseMove (fabric.js:13743:1)
    at klass._onMouseMove (fabric.js:13332:1)
_setCursorFromEvent	@	fabric.js:13911
__onMouseMove	@	fabric.js:13743
_onMouseMove	@	fabric.js:13332
```

Source

```
import React from "react";

import { FabricImage } from "fabric";
import { FabricJSCanvas, useFabricJSEditor } from "fabricjs-react";
import "./styles.css";

export default function App() {
  const { editor, onReady } = useFabricJSEditor();
  const onAddCircle = () => {
    editor.addCircle();

    FabricImage.fromURL("https://www.searchenginejournal.com/wp-content/uploads/2019/07/the-essential-guide-to-using-images-legally-online.png").then((img) => {

      editor.canvas.add(img);

    });


  };
  const onAddRectangle = () => {
    editor.addRectangle();
  };

  return (
    <div className="App">
      <h1>FabricJS React Sample</h1>
      <button onClick={onAddCircle}>Add circle</button>
      <button onClick={onAddRectangle}>Add Rectangle</button>
      <FabricJSCanvas className="sample-canvas" onReady={onReady} />
    </div>
  );
}

```

Thanks,
Luigi

**Comment by JamesGriz** [comment]
I am not getting the error that @luigimalago is but am also having issues with rendering images based on the provided code snippets.

Here is my codesandbox:
https://codesandbox.io/p/sandbox/frosty-mcclintock-mmppqx

Does anyone have a working version?

**Comment by asotog** [comment]
It seems this callback is not working 
```
FabricImage.fromURL(
        "https://www.searchenginejournal.com/wp-content/uploads/2019/07/the-essential-guide-to-using-images-legally-online.png",
        (img) => {
          console.log("adding image");
          img.scale(1).set({ left: 0, top: 0 });
          editor.canvas.add(img);
          editor.canvas.renderAll();
        }
      );
```
> I am not getting the error that [@luigimalago](https://github.com/luigimalago) is but am also having issues with rendering images based on the provided code snippets.
> 
> Here is my codesandbox: https://codesandbox.io/p/sandbox/frosty-mcclintock-mmppqx
> 
> Does anyone have a working version?

**Comment by asotog** [comment]
It seems something related to images loading changed on latest fabric version @luigimalago , this seems to work, updated repo readme file, however this is not fabricjs-react issue, is more a breaking change on fabricjs core
```
useEffect(() => {
    console.log(editor, editor?.canvas);
    if (editor && editor.canvas) {
      console.log("start adding image");
      FabricImage.fromURL(
        "https://www.searchenginejournal.com/wp-content/uploads/2019/07/the-essential-guide-to-using-images-legally-online.png"
      ).then((img) => {
        console.log("adding image");
        // img.scale(1).set({ left: 0, top: 0 });
        editor.canvas.add(img);
        editor.canvas.renderAll();
      });
    }
  }, [editor]);
```

![Image](https://github.com/user-attachments/assets/c7de06a5-8ab1-48b5-90ec-1af9831e1344)
